require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WordwsController do

  # This should return the minimal set of attributes required to create a valid
  # Wordw. As you add validations to Wordw, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all wordws as @wordws" do
      wordw = Wordw.create! valid_attributes
      get :index
      assigns(:wordws).should eq([wordw])
    end
  end

  describe "GET show" do
    it "assigns the requested wordw as @wordw" do
      wordw = Wordw.create! valid_attributes
      get :show, :id => wordw.id.to_s
      assigns(:wordw).should eq(wordw)
    end
  end

  describe "GET new" do
    it "assigns a new wordw as @wordw" do
      get :new
      assigns(:wordw).should be_a_new(Wordw)
    end
  end

  describe "GET edit" do
    it "assigns the requested wordw as @wordw" do
      wordw = Wordw.create! valid_attributes
      get :edit, :id => wordw.id.to_s
      assigns(:wordw).should eq(wordw)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Wordw" do
        expect {
          post :create, :wordw => valid_attributes
        }.to change(Wordw, :count).by(1)
      end

      it "assigns a newly created wordw as @wordw" do
        post :create, :wordw => valid_attributes
        assigns(:wordw).should be_a(Wordw)
        assigns(:wordw).should be_persisted
      end

      it "redirects to the created wordw" do
        post :create, :wordw => valid_attributes
        response.should redirect_to(Wordw.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved wordw as @wordw" do
        # Trigger the behavior that occurs when invalid params are submitted
        Wordw.any_instance.stub(:save).and_return(false)
        post :create, :wordw => {}
        assigns(:wordw).should be_a_new(Wordw)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Wordw.any_instance.stub(:save).and_return(false)
        post :create, :wordw => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested wordw" do
        wordw = Wordw.create! valid_attributes
        # Assuming there are no other wordws in the database, this
        # specifies that the Wordw created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Wordw.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => wordw.id, :wordw => {'these' => 'params'}
      end

      it "assigns the requested wordw as @wordw" do
        wordw = Wordw.create! valid_attributes
        put :update, :id => wordw.id, :wordw => valid_attributes
        assigns(:wordw).should eq(wordw)
      end

      it "redirects to the wordw" do
        wordw = Wordw.create! valid_attributes
        put :update, :id => wordw.id, :wordw => valid_attributes
        response.should redirect_to(wordw)
      end
    end

    describe "with invalid params" do
      it "assigns the wordw as @wordw" do
        wordw = Wordw.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Wordw.any_instance.stub(:save).and_return(false)
        put :update, :id => wordw.id.to_s, :wordw => {}
        assigns(:wordw).should eq(wordw)
      end

      it "re-renders the 'edit' template" do
        wordw = Wordw.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Wordw.any_instance.stub(:save).and_return(false)
        put :update, :id => wordw.id.to_s, :wordw => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested wordw" do
      wordw = Wordw.create! valid_attributes
      expect {
        delete :destroy, :id => wordw.id.to_s
      }.to change(Wordw, :count).by(-1)
    end

    it "redirects to the wordws list" do
      wordw = Wordw.create! valid_attributes
      delete :destroy, :id => wordw.id.to_s
      response.should redirect_to(wordws_url)
    end
  end

end
