require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WordsController do

  # This should return the minimal set of attributes required to create a valid
  # Wordw. As you add validations to Wordw, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { :name => 'foo'}
  end

  describe "GET index" do
    it "assigns all wordws as @wordws" do
      word = Word.create! valid_attributes
      get :index
      assigns(:words).should eq([word])
    end
  end

  describe "GET #index" do
    it "paginates" do
      word = Word.create! valid_attributes
      get :index
      assigns(:words).first.should be_kind_of Hash
    end
  end

end
